code_column_names = ['Case #',
		'Shooter Last Name',
		'Shooter First Name',
		'Full date',
		'Day of the week',
		'Day',
		'Month',
		'Year',
		'Street Number',
		'Street Name',
		'City',
		'Stacode_column_nameste',
		'County',
		'Zip Code',
		'Latitude',
		'Longitude',
		'State code',
		'Region',
		'Urban, suburban, or rural area',
		'Metro/Micro Statistical Area Type',
		'Primary Location',
		'Insider or Outsider',
		'Workplace Shooting',
		'Multiple Locations',
		'Other Location',
		'Armed person on scene',
		'Specify armed person on scene (if applicable)',
		'Number killed',
		'Number injured',
		'Kidnapping or hostage element',
		'Age',
		'Gender',
		'Race',
		'Height',
		'Weight',
		'Immigrant',
		'Sexual orientation',
		'Religion',
		'Education',
		'School performance',
		'School performance specified',
		'Birth order',
		'Number of siblings',
		'Number of older siblings',
		'Number of younger siblings ',
		'Relationship status',
		'Children',
		'Employment status',
		'Employment type',
		'Military service',
		'Military branch',
		'Community involvement',
		'Community involvement specified',
		'Known to Police or FBI',
		'Criminal Record',
		'Part 1 Crimes',
		'Part 2 Crimes',
		'Highest level of criminal justice involvement',
		'Animal Abuse',
		'History of Physical Altercations',
		'History of domestic abuse',
		'Domestic abuse specified',
		'History of sexual offenses ',
		'Gang association',
		'Terror group association',
		'Hate group association',
		'Played violent video games',
		'Bully ',
		'Bullied ',
		'Raised by single parent',
		'Parental separation or divorce',
		'Suicide of parent',
		'Death of parent',
		'Childhood trauma',
		'Physical Abuse',
		'Sexual Abuse',
		'Emotional Abuse',
		'Neglect',
		'Childhood socioeconomic status',
		'Mother was violently treated',
		'Parent substance abuse',
		'Parent criminal record',
		'Family member incarcerated',
		'Adult trauma',
		'Recent stressor / triggering event',
		'Signs of being in crisis ',
		'Timeframe of when signs of crisis began',
		'Inability to perform daily tasks',
		'Notably depressed mood',
		'Unusually calm or happy',
		'Rapid mood swings',
		'Increased agitation',
		'Abusive behavior',
		'Isolation',
		'Losing touch with reality ',
		'Paranoia',
		'Suicidality',
		'Hospitalization for psychiatric reasons',
		'Voluntary or involuntary hospitalization',
		'Prior counseling',
		'Voluntary or mandatory counseling',
		'Prescribed psychiatric medication',
		'Psychiatric medication specified ',
		'Treatment',
		'Mental illness',
		'FASD (Fetal Alcohol Spectrum Disorder)',
		'Known family history of mental health issues',
		'Autism spectrum disorder',
		'Substance use and abuse',
		'Health issues',
		'Specify health issues',
		'Head injury / Possible brain injury',
		'Known prejudices',
		'Motive: Racism',
		'Motive: Religious hate ',
		'Motive: Misogyny',
		'Motive: Homophobia',
		'Motive: Employment issue ',
		'Motive: Economic issue ',
		'Motive: Legal issue',
		'Motive: Relationship issues ',
		'Motive: Interpersonal conflict ',
		'Motive: Fame-seeking',
		'Motive: Other ',
		'Motive: Unknown',
		'Role of psychosis in the shooting',
		'Social media use',
		'Leakage prior to the shooting',
		'Leakage - How?',
		'Leakage - Who?',
		'Leakage - Specific?',
		'Interest in past mass violence',
		'Relationship with other shooting(s)',
		'Specify relationship to other shooting(s)',
		'Legacy token',
		'Connection to pop culture',
		'Specify pop culture connection',
		'Significant prior planning',
		'Performance',
		'Notable or obsessive interest in firearms',
		'Firearm proficiency',
		'Total weapons brought to the scene',
		'Other weapons or gear',
		'Specify other weapons or gear',
		'On scene outcome',
		'Who Killed Shooter On Scene',
		'Attempt to flee',
		'Insanity defense at trial',
		'Criminal sentence']